[package]
name = "crud_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = "0.19.10"
actix-web ="4"
serde ={ version = "1.0.197", features = ["derive"]}
sqlx = { version = "=0.8.1", features = ["sqlite"] }
